### ISSUE TITLE
rake db:create leads to "database is not existing"

### ISSUE THREAD

**Issue by Faffnir** [Barzahlen/tidus#9]
If you try to create a db with tidus in place, you will get following error:
`rake aborted!
FATAL:  Database „<database-name>“ is not existing
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in`initialize'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in`connect'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in`new'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in`new_connection'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in`acquire_connection'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in`checkout'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in`connection'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:567:in `retrieve_connection'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.2.1/lib/active_record/connection_handling.rb:113:in`retrieve_connection'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.2.1/lib/active_record/connection_handling.rb:87:in `connection'
/usr/local/rvm/gems/ruby-2.1.1/gems/tidus-1.0.5/lib/tidus/strategies/base_selector.rb:6:in`anonymize'
/usr/local/rvm/gems/ruby-2.1.1/gems/tidus-1.0.5/lib/tidus/anonymization.rb:68:in `block in anonymizes'
/usr/local/rvm/gems/ruby-2.1.1/gems/tidus-1.0.5/lib/tidus/anonymization.rb:55:in`each'
/usr/local/rvm/gems/ruby-2.1.1/gems/tidus-1.0.5/lib/tidus/anonymization.rb:55:in `anonymizes'
/var/www/---/models/---.rb:23:in`class:Address'
/var/www/---/models/---.rb:2:in `<module:M1>'
/var/www/---/models/---.rb:1:in`<top (required)>'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`block in require'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`require'
/var/www/---/Rakefile:11:in `block in <top (required)>'
/var/www/---/Rakefile:11:in`each'
/var/www/---/Rakefile:11:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in`eval'
/usr/local/rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'`

**Comment by tobischo** [comment]
The issue appears to be caused by hooking the anonymizes methods into the model
Tidus automatically tried to determine the database adapter
Currently it requires an active connection for that. This obviously fails because the database to which the connection should be established does not exist

See https://github.com/Barzahlen/tidus/blob/master/lib/tidus/strategies/base_selector.rb#L6

**Comment by Faffnir** [comment]
I think it is save to say that this issue can be cleaned up?

**Comment by tobischo** [comment]
Yeah, I do not think we will address it here + we made some other changes in the meantime
